---
title: "Filtered Historical Simulation"
author: "Jan Heinrich Schlegel"
date: "2022-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE)
library(rugarch)
library(rmgarch)
library(xts)
library(parallel)
library(tidyverse)
library(expm)
library(matlib)
```

## Filtered Historical Simulation
```{r}
## read the data
# setwd("C:/Users/Jan Schlegel/Desktop/BachelorThesis/Bachelor Thesis Code/Data")
setwd("C:/Users/jansc/Desktop/Bachelor Thesis/BachelorThesis/Bachelor Thesis Code/Data")
FFCFactors.df <- read.csv("FFCFactors.csv", header = TRUE)
stocks.plret.df <- read.csv("StockPlrets.csv", header = TRUE)
portfolio.plret.df <- data.frame(Date = stocks.plret.df$Date, Portfolio = apply(stocks.plret.df[,-1], 1, mean))

## Convert to time series
FFCFactors.ts <- xts(FFCFactors.df[,-1], order.by = as.Date(FFCFactors.df$Date))
stocks.plret.ts <- xts(stocks.plret.df[,-1], order.by = as.Date(stocks.plret.df$Date))
portfolio.plret.ts <- xts(portfolio.plret.df[,-1], order.by = as.Date(portfolio.plret.df$Date))

## Detect how many cores are available for parallelizing
numcores <- detectCores()
```

```{r}
## Univariate
returns <- data.frame(Date = portfolio.plret.df[,1], Returns = portfolio.plret.df[,2])
specGARCH <- ugarchspec(mean.model = list(armaOrder = c(0,0), include.mean = FALSE), distribution = "sstd")
fitGARCH <- ugarchfit(specGARCH, portfolio.plret.ts)
returns$vol <- sigma(fitGARCH)
returns$scaled <- returns[,2]/returns$vol
z.bootstrapped <- sample(returns$scaled, 100000, replace = TRUE)
hist(z.bootstrapped, col = "lightblue", probability = TRUE, breaks = 30)
lines(density(z.bootstrapped), col = "firebrick")
fhs <- quantile(z.bootstrapped, 0.05)*as.numeric(sigma(ugarchforecast(fitGARCH, n.ahead = 1)))


#' @param returndata return data for which we want to calculate VaR
#' @param n.window length of rolling window
#' @param specGARCH ugarchspec object containing the specs for ugarchfit
#' @param nboot number of bootstrap draws of historical shocks
#' @param VaR_level Vector w/ VaR quantiles
fhs.window <- function(returndata, n.window = length(returndata)-1000, specGARCH, nboot, VaR_level=c(0.01,0.05)){
  fhs <- matrix(numeric(n.window*length(VaR_level)), nrow = n.window, ncol = length(VaR_level))
  for (i in 1:n.window){
    end <- i+999
    stocks.window <- returndata[i:end]
    fit_GARCH <- ugarchfit(specGARCH, stocks.window)
    z.scaled <- stocks.window/sigma(fit_GARCH)
    z.bootstrapped <- sample(z.scaled, nboot, replace = TRUE)
    fhs[i,] <- quantile(z.bootstrapped, VaR_level)*as.numeric(sigma(ugarchforecast(fitGARCH, n.ahead = 1)))
  }
  fhs
}

specGARCH <- ugarchspec(mean.model = list(armaOrder = c(0,0), include.mean = FALSE), distribution = "sstd")
start <- Sys.time()
VaR_fhs <- fhs.window(returndata = portfolio.plret.ts, specGARCH = specGARCH, nboot = 100000)
VaR_fhs
end <- Sys.time()
end-start
VaRplot(0.01, portfolio.plret.ts[-c(1:1000)], VaR_fhs[,1])
VaRplot(0.05, portfolio.plret.ts[-c(1:1000)], VaR_fhs[,2])
VaRTest(0.01, portfolio.plret.ts[-c(1:1000)], VaR_fhs[,1])
VaRTest(0.05, portfolio.plret.ts[-c(1:1000)], VaR_fhs[,2])
```


```{r}
## Multivariate
uniGARCH.spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)), mean.model = list(armaOrder = c(0,0), include.mean = TRUE), distribution = "norm")
multiGARCH.spec <- multispec(replicate(4, uniGARCH.spec))
DCC.spec <- dccspec(multiGARCH.spec, dccOrder = c(1,1), distribution =  "mvnorm")
fitDCCGARCH <- dccfit(DCC.spec, FFCFactors.ts[,-4])
fitDCCGARCH
# gamma <- rcor(fitDCCGARCH, type = "R")
# stand.factor <- array(dim=c(4,4,length(portfolio.plret.ts)))
# V <- eigen(matr)$vectors
# L <- eigen(matr)$values
# # square root
# Sqrt <- V %*% diag(sqrt(L)) %*% t(V)
# for (i in 1:length(portfolio.plret.ts)) stand.factor[,,i] <- inv(sqrtm(gamma[,,1]))
stdresid <- fitDCCGARCH@mfit$stdresid
nboot <- 100000
boot.ind <- sample(1:length(portfolio.plret.ts), nboot, replace = TRUE)
boot.z <- matrix(numeric(4*nboot), nrow = nboot, ncol = 4)
for (i in 1:nboot)boot.z[i,]<-stdresid[boot.ind[i],]
# boot.z <- apply(boot.z, 1, function(x))# choose historical shock w/ given index
summary(boot.z)
par(mfrow=c(2,2))
for (i in 1:4) hist(boot.z[,i], col ="lightblue", breaks = 50)

DCC.forecast <- dccforecast(fitDCCGARCH, n.ahead = 1)
cov.mat <- matrix(DCC.forecast@mforecast$H[[1]], nrow = 4)# rcov(DCC.forecast, output = "matrix")
cov.mat
dim(boot.z)
sqrt.cov <- sqrtm(cov.mat)
returns <- apply(boot.z, 1, function(x)x%*%sqrt.cov)
dim(returns)
returns.weighted <- apply(returns, 2, function(x)mean(x))
(VaR_multi_fhs <- quantile(returns.weighted, c(0.01, 0.05)))
length(returns.weighted)
hist(returns.weighted, col = "lightblue", breaks = 30)
```

