---
title: "MSGARCH"
author: "Jan Heinrich Schlegel"
date: "2022-08-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and Manipulating the Data
```{r}
library(tidyverse)
library(magrittr)
library(yfR)
library(zoo)
library(psych)
library(tseries)
library(broom)
library(xts)

tickers <- c("KO", "XOM", "GE", "IBM", "CVX", "RTX", "PG", "CAT", "BA", "MRK")
stock_data <- yf_get(tickers, first_date = "2000-12-29", last_date = "2011-12-30", 
                     freq_data = "daily",  type_return = "log")
stock_data

# Only the first log return for each of the stocks is NA
# i.e. our actual log returns begin on the 1st of January 2001
sum(is.na(stock_data$ret_adjusted_prices))

for (ticker_nr in 1:10){
  assign(tickers[ticker_nr], stock_data %>% filter(ticker == tickers[ticker_nr]) %>% 
           select(ticker, ref_date, ret_adjusted_prices) %>% na.omit())
}
View(PG)

stocks.lret.df <- data.frame(Date = KO$ref_date, KO = KO$ret_adjusted_prices, XOM = XOM$ret_adjusted_prices, GE = GE$ret_adjusted_prices,
                        IBM = IBM$ret_adjusted_prices, CVX = CVX$ret_adjusted_prices, RTX = RTX$ret_adjusted_prices, PG = PG$ret_adjusted_prices,
                        CAT = CAT$ret_adjusted_prices, BA = BA$ret_adjusted_prices, MRK = MRK$ret_adjusted_prices)

stocks.lret.df

stocks.perclret.df <- data.frame(Date = KO$ref_date, apply(stocks.lret.df[,-1], 2, function(x)100*x))
stocks.perclret.df


# Calculate portfolio returns of equally weighted portfolio
portfolio.weights <- rep(1/10, 10)
portfolio.plret.df <- data.frame(Date = stocks.perclret.df$Date, plret = apply(stocks.perclret.df[,-1], 1, function(x)x%*%portfolio.weights))
# Alternatively: portfolio.perclret <- apply(stocks.perclret.df[,-1], 1, mean)

# Convert to time series
portfolio.plret.ts <- xts(portfolio.plret.df$plret, order.by = portfolio.plret.df$Date)
plot(portfolio.plret.ts)

stocks.plret.ts <- xts(stocks.perclret.df[,-1], order.by = stocks.perclret.df$Date)
stocks.plret.ts
```

```{r}
library(rugarch)
library(MSGARCH)
library(parallel)
############ Read Ardia et al. (see MSGARCH documentation)
set.seed(42)
spec <- CreateSpec(variance.spec = list(model = c("sGARCH", "sGARCH")), distribution.spec = list(distribution = c("norm", "norm"), switch.spec = list(do.mix = TRUE)))

n <- length(stocks.perclret.df[,1])
VaR <- numeric(n)
start_time <- Sys.time()
# fit <- list()
# forecast <- list()

n.window <- n-1000

for (i in 1:n.window){
  end <- i+999
  stocks.window <- stocks.plret.ts[1:end]
  fit.mixed <- FitMCMC(spec = spec, stocks.window)
  VaR[i] <- as.numeric(Risk(fit.mixed, alpha = 0.01, do.es = FALSE, nahead = 1L)$VaR)
}
end_time <- Sys.time()
end_time-start_time

end <- n
start <- end-length(VaR)
VaRplot(0.05, portfolio.plret.ts[start:end], VaR)
```

